### ISSUE TITLE
Stylelint conflict with Prettier about `grid-template-areas`

### ISSUE THREAD

**Issue by yasincaliskan** [Hipo/stylelint-config-hipo-base#18]
Prettier formats `grid-template-areas` but this is not proper for Stylelint `declaration-colon-space-after` rule.
```scss
.other-stats-item {
    grid-template-areas:
      "value ."
      "name time-period";
}
```

`  Expected single space after ":"   declaration-colon-space-after`
